### ISSUE TITLE
typo: soparee_config in filter.py ?

### ISSUE THREAD

**Issue by pingus69** [bishoph/sopare#6]
perhaps there is a typo in filter.py:

./sopare/filter.py:                progessive += progessive * soparee.config.PROGRESSIVE_FACTOR

Must be sopare.config?
Sometimes I get a

Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/pi/sopare_1.4.0/sopare/sopare/buffering.py", line 44, in run
    self.proc.check_silence(buf)
  File "/home/pi/sopare_1.4.0/sopare/sopare/processing.py", line 76, in check_silence
    self.prepare.prepare(buf, volume)
  File "/home/pi/sopare_1.4.0/sopare/sopare/prepare.py", line 127, in prepare
    self.tokenize(meta)
  File "/home/pi/sopare_1.4.0/sopare/sopare/prepare.py", line 52, in tokenize
    self.filter.filter(self.buffer, meta)
  File "/home/pi/sopare_1.4.0/sopare/sopare/filter.py", line 129, in filter
    chunked_norm = self.get_chunked_norm(nfft)
  File "/home/pi/sopare_1.4.0/sopare/sopare/filter.py", line 64, in get_chunked_norm
    progessive += progessive * soparee.config.PROGRESSIVE_FACTOR
NameError: global name 'soparee' is not defined

**Comment by bishoph** [comment]
Thanks, fixed it.

How could such an issue even creep into the code ... ?!?
