### ISSUE TITLE
Loop with HIGH_FREQ = 1000

### ISSUE THREAD

**Issue by MonDieux** [bishoph/sopare#86]
I trained 3 words. Sopare works quite ok. I changed parms like in your blueprint and changed HIGH_FREQ to 1000.
Without a new compile step, sopar is running in an error;
Process buffering queue:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/pi/dev/sopare/sopare/buffering.py", line 43, in run
    self.proc.check_silence(buf)
  File "/home/pi/dev/sopare/sopare/processing.py", line 74, in check_silence
    self.prepare.prepare(buf, volume)
  File "/home/pi/dev/sopare/sopare/prepare.py", line 125, in prepare
    self.tokenize(meta)
  File "/home/pi/dev/sopare/sopare/prepare.py", line 50, in tokenize
    self.filter.filter(self.buffer, meta)
  File "/home/pi/dev/sopare/sopare/filter.py", line 126, in filter
    chunked_norm = self.get_chunked_norm(nfft)
  File "/home/pi/dev/sopare/sopare/filter.py", line 61, in get_chunked_norm
    progessive += progessive * pf
NameError: global name 'pf' is not defined
INFO:sopare.recorder:Buffering not alive, stop recording
INFO:sopare.recorder:stop endless recording
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
Process worker for filtered data:
Traceback (most recent call last):
    func(*targs, **kargs)

After this, sopare is a "Zomie"-process: no ending, no reaction, nothing. After a vew Cntl-C sopare stopps an I have an prompt.
When I start sopare again,  with -l -v, the protocollation starts, but no reaction for any input.

After reboot and change the parm to 600, I have the normal reaction.

**Comment by bishoph** [comment]
This bug is already fixed in testing branch...
